version: "1.0"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-e_commerce
    restart: always
    environment:
      - POSTGRES_USER=$DB_POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$DB_POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - ${DEFAULT_VOL_DIR:-./}docker-data/postgresql/:/var/lib/postgresql/data
